[package]
name = "raoc"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
reqwest = { version = "0.11", features = ["blocking", "json"] }
dotenv = "0.15.0"
